post_install() {
    echo -e "########################################################################################################"
    echo -e "## The theme.txt file can be found in /boot/grub/themes/grub-theme-heisenberg-chemistry-git/theme.txt ##"
    echo -e "########################################################################################################"
}

post_upgrade() {
    post_install
}

